pipeline {
    agent { 
        docker { 
            image 'node:12' 
        } 
    }

    stages {     
        stage('install dependencies') {
            steps {
                sh 'node --version'
                sh 'npm --version'
                sh 'npm install'
            }
        }
        
        stage('test') {
            steps {
                sh 'npm run test:ci'
            }
        }
    }
    
    post {
        success {
            junit 'coverage/junit/junit.xml'
        }        
    }
}
