pipeline {
    agent { 
        docker { 
            image 'node:12' 
        } 
    }
    
    environment {
        REPO_URL = 'git@github.com:juliocesar-io/jenkins-serverless.git'
        SHORT_BRANCH = "${BRANCH}".replace("origin/", "")
    }
    
    stages {     
        stage('install dependencies') {
            steps {
                sh 'node --version'
                sh 'npm --version'
                sh 'npm install'
            }
        }
        
        stage('test') {
            steps {
                sh 'npm run test:ci'
            }
        }
    }
    
    post {
        success {
            junit 'coverage/junit/junit.xml'
        }        
    }
}